INSERT INTO problems (id, title, slug, "problemLink", platform, difficulty, "createdAt") VALUES
-- Blind 75 problems
(uuidv4(),'Two Sum','two-sum','https://leetcode.com/problems/two-sum/','LeetCode','Easy',NOW()),
(uuidv4(),'Best Time to Buy and Sell Stock','best-time-to-buy-and-sell-stock','https://leetcode.com/problems/best-time-to-buy-and-sell-stock/','LeetCode','Easy',NOW()),
(uuidv4(),'Contains Duplicate','contains-duplicate','https://leetcode.com/problems/contains-duplicate/','LeetCode','Easy',NOW()),
(uuidv4(),'Product of Array Except Self','product-of-array-except-self','https://leetcode.com/problems/product-of-array-except-self/','LeetCode','Medium',NOW()),
(uuidv4(),'Maximum Subarray','maximum-subarray','https://leetcode.com/problems/maximum-subarray/','LeetCode','Medium',NOW()),
(uuidv4(),'Maximum Product Subarray','maximum-product-subarray','https://leetcode.com/problems/maximum-product-subarray/','LeetCode','Medium',NOW()),
(uuidv4(),'Find Minimum in Rotated Sorted Array','find-minimum-rotated-array','https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/','LeetCode','Medium',NOW()),
(uuidv4(),'Search in Rotated Sorted Array','search-rotated-array','https://leetcode.com/problems/search-in-rotated-sorted-array/','LeetCode','Medium',NOW()),
(uuidv4(),'3Sum','three-sum','https://leetcode.com/problems/3sum/','LeetCode','Medium',NOW()),
(uuidv4(),'Container With Most Water','container-with-most-water','https://leetcode.com/problems/container-with-most-water/','LeetCode','Medium',NOW()),
(uuidv4(),'Climbing Stairs','climbing-stairs','https://leetcode.com/problems/climbing-stairs/','LeetCode','Easy',NOW()),
(uuidv4(),'Coin Change','coin-change','https://leetcode.com/problems/coin-change/','LeetCode','Medium',NOW()),
(uuidv4(),'Longest Increasing Subsequence','longest-increasing-subsequence','https://leetcode.com/problems/longest-increasing-subsequence/','LeetCode','Medium',NOW()),
(uuidv4(),'Longest Common Subsequence','longest-common-subsequence','https://leetcode.com/problems/longest-common-subsequence/','LeetCode','Medium',NOW()),
(uuidv4(),'Word Break','word-break','https://leetcode.com/problems/word-break/','LeetCode','Medium',NOW()),
(uuidv4(),'Combination Sum','combination-sum','https://leetcode.com/problems/combination-sum/','LeetCode','Medium',NOW()),
(uuidv4(),'House Robber','house-robber','https://leetcode.com/problems/house-robber/','LeetCode','Medium',NOW()),
(uuidv4(),'House Robber II','house-robber-ii','https://leetcode.com/problems/house-robber-ii/','LeetCode','Medium',NOW()),
(uuidv4(),'Decode Ways','decode-ways','https://leetcode.com/problems/decode-ways/','LeetCode','Medium',NOW()),
(uuidv4(),'Unique Paths','unique-paths','https://leetcode.com/problems/unique-paths/','LeetCode','Medium',NOW()),

-- Striver SDE sample
(uuidv4(),'Set Matrix Zeroes','set-matrix-zeroes','https://leetcode.com/problems/set-matrix-zeroes/','LeetCode','Medium',NOW()),
(uuidv4(),'Pascal Triangle','pascals-triangle','https://leetcode.com/problems/pascals-triangle/','LeetCode','Easy',NOW()),
(uuidv4(),'Next Permutation','next-permutation','https://leetcode.com/problems/next-permutation/','LeetCode','Medium',NOW()),
(uuidv4(),'Kadane Algorithm','kadane-algorithm','https://leetcode.com/problems/maximum-subarray/','LeetCode','Medium',NOW()),
(uuidv4(),'Merge Intervals','merge-intervals','https://leetcode.com/problems/merge-intervals/','LeetCode','Medium',NOW()),
(uuidv4(),'Rotate Matrix','rotate-matrix','https://leetcode.com/problems/rotate-image/','LeetCode','Medium',NOW()),
(uuidv4(),'Search Matrix','search-2d-matrix','https://leetcode.com/problems/search-a-2d-matrix/','LeetCode','Medium',NOW()),
(uuidv4(),'Pow(x,n)','pow-x-n','https://leetcode.com/problems/powx-n/','LeetCode','Medium',NOW()),
(uuidv4(),'Majority Element','majority-element','https://leetcode.com/problems/majority-element/','LeetCode','Easy',NOW()),
(uuidv4(),'Majority Element II','majority-element-ii','https://leetcode.com/problems/majority-element-ii/','LeetCode','Medium',NOW()),
(uuidv4(),'Reverse Linked List','reverse-linked-list','https://leetcode.com/problems/reverse-linked-list/','LeetCode','Easy',NOW()),
(uuidv4(),'Middle of Linked List','middle-of-linked-list','https://leetcode.com/problems/middle-of-the-linked-list/','LeetCode','Easy',NOW()),
(uuidv4(),'Linked List Cycle','linked-list-cycle','https://leetcode.com/problems/linked-list-cycle/','LeetCode','Easy',NOW()),
(uuidv4(),'Remove Nth Node','remove-nth-node','https://leetcode.com/problems/remove-nth-node-from-end-of-list/','LeetCode','Medium',NOW()),
(uuidv4(),'Add Two Numbers','add-two-numbers','https://leetcode.com/problems/add-two-numbers/','LeetCode','Medium',NOW()),
(uuidv4(),'Intersection of Two Linked Lists','intersection-linked-lists','https://leetcode.com/problems/intersection-of-two-linked-lists/','LeetCode','Easy',NOW()),
(uuidv4(),'Flatten Binary Tree','flatten-binary-tree','https://leetcode.com/problems/flatten-binary-tree-to-linked-list/','LeetCode','Medium',NOW()),
(uuidv4(),'Binary Tree Inorder Traversal','binary-tree-inorder','https://leetcode.com/problems/binary-tree-inorder-traversal/','LeetCode','Easy',NOW()),
(uuidv4(),'Maximum Depth Binary Tree','max-depth-binary-tree','https://leetcode.com/problems/maximum-depth-of-binary-tree/','LeetCode','Easy',NOW()),
(uuidv4(),'Same Tree','same-tree','https://leetcode.com/problems/same-tree/','LeetCode','Easy',NOW());